build: Vector.cpp Hashtable.cpp StringBuilder.cpp LinkedList.cpp MyHashtable.cpp
	g++ Vector.cpp -o Vector -std=c++11
	g++ Hashtable.cpp -o Hashtable -std=c++11
	g++ StringBuilder.cpp -o StringBuilder -std=c++11
	g++ LinkedList.cpp -o LinkedList -std=c++11
	g++ MyHashtable.cpp -o MyHashtable -std=c++11

run-Vector: Vector
	./Vector

run-Hashtable: Hashtable
	./Hashtable

run-StringBuilder: StringBuilder
	./StringBuilder

run-LinkedList: LinkedList
	./LinkedList

run-MyHashtable: MyHashtable
	./MyHashtable

clean:
	rm -rf Vector Hashtable StringBuilder LinkedList MyHashtable